### ISSUE TITLE
Current status?

### ISSUE THREAD

**Issue by ghost** [google/capsicum-linux#10]
Is this still a work in progress or has it been superceded in some way? I liked Capsicum in FreeBSD quite a bit.

http://capsicum-linux.org seems to be dead.

**Comment by pmetzger** [comment]
@teran-mckinney There certainly hasn't been much said about it in a very, very long time.

**Comment by ghost** [comment]
Ah, that's a shame. Thanks for confirming!

Being able to lock down threads or subprocesses makes so much sense.

**Comment by daviddrysdale** [comment]
Yeah, I'm afraid there's no work being done on the Linux port at present.

However, there are a couple of recent bits of Linux activity that overlap with some of the ancillary Capsicum features, and so may be of interest:
 - [pidfds](https://lwn.net/Articles/773459/) are somewhat analogous to Capsicum's process descriptors.
 - There's [a proposed patchset](https://lkml.org/lkml/2019/5/20/1064) that [includes functionality](https://lkml.org/lkml/2019/5/20/1071) similar to path policing in capability mode (which got pulled out as a separate `O_BENEATH` flag in the Linux Capsicum port)

**Comment by pmetzger** [comment]
> I'm afraid there's no work being done on the Linux port at present.

That's an enormous shame. Capsicum would have been a wonderful thing for Linux. What was the reason that the effort died?
