### ISSUE TITLE
Project status?

### ISSUE THREAD

**Issue by davidchisnall** [google/capsicum-linux#11]
Is this project still alive?  The link for status goes to a domain squatting site and it appears as if the repo hasn't been touched for a few years.

**Comment by daviddrysdale** [comment]
There hasn't been anyone actively working on Capsicum for Linux for a few years now.   

Thanks for reminding me to update things; I've removed the link to the lapsed domain and added a note about status.

**Comment by vt-alt** [comment]
@daviddrysdale Can you alaborate a bit on why it's no longer developed? Thanks!
