### ISSUE TITLE
How would I responsibly disclose a new security issue?

### ISSUE THREAD

**Issue by erights** [google/capsicum-linux#4]
Back when many of us were using code.google, the New Issue button would take us to a form in which we could mark the new issue to be private/security-related. Likewise, projects that use bugzilla accommodate the submission of private/security-related bugs. I see no such form here. There are plenty of security-critical projects hosted on github that must face this same issue. What do you/they do?

Note that I do not have such an issue to disclose against capsicum-linux at this time. I ask now for another reason.

**Comment by daviddrysdale** [comment]
I don't think this is currently possible via GitHub (as [others have noted/are tracking](https://github.com/isaacs/github/issues/37)).

In practice, I guess dropping a private email to the maintainers would be the best approach.

(In theory, having an [official documented policy](https://github.com/linuxfoundation/cii-best-practices-badge/blob/master/doc/criteria.md#vulnerability_report_process) would be a good idea; I don't think it's necessary for this repo as there are very few live users as yet.)

**Comment by erights** [comment]
This situation is unfortunate but not at all specific to this project, so closing the issue here. Thanks for the info.
