### ISSUE TITLE
futexwakeup and epollwait appear to not be allowed in capability mode [EOM]

### ISSUE THREAD

**Issue by benlaurie** [google/capsicum-linux#6]

**Comment by benlaurie** [comment]
BTW, these are used by Go grpc.

**Comment by daviddrysdale** [comment]
From the [man page](http://man7.org/linux/man-pages/man2/epoll_wait.2.html), `epoll_wait` looks like it should be OK for capability mode (no global namespace involved), so I can add that to the whitelist.

Not sure about `futexwakeup` -- there's only a `futex` syscall in the [master syscall list](https://github.com/torvalds/linux/blob/v4.13/arch/x86/entry/syscalls/syscall_64.tbl).  `futex(2)` can apparently take a `FUTEX_WAKE` operation (and that does looks like what [Go uses](https://github.com/golang/go/blob/master/src/runtime/os_linux.go#L68)), but the current capability mode filter [should allow](https://github.com/google/capsicum-test/blob/dev/libcaprights/linux-bpf-capmode.h#L36) that through.

**Comment by benlaurie** [comment]
The error is ECAPMODE.

**Comment by benlaurie** [comment]
Actually, weirdly, in the futex case it is -ECAPMODE. Maybe just fix the other one and we see what happens?

**Comment by daviddrysdale** [comment]
Getting `-ECAPMODE` sounds like there some missing syscall wrapper functionality somewhere -- kernel code typically returns `-ESOMETHING` and glibc or equivalent translates to `rc, errno := -1, ESOMETHING`.

**Comment by daviddrysdale** [comment]
[Commit 1291d2b0a75e](https://github.com/google/capsicum-test/commit/1291d2b0a75e2d22d73f134e8550fb5452aa3b81) over at the userspace library should allow `epoll_*` syscalls.

**Comment by benlaurie** [comment]
Tested, gRPC works (at least so far).
